
name: CI

on: [ push ]

jobs:
  php:
    name: Run PHP checks (phpcs, phpstan)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
      - name: Composer Install
        run: composer update
      - name: Run checks
        run: composer check
