name: Tests

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    test:
        runs-on: ${{ matrix.os }}

        services:
          meilisearch:
            image: getmeili/meilisearch:latest
            ports:
              - 7700:7700
            env:
              MEILI_MASTER_KEY: masterKey
              MEILI_NO_ANALYTICS: true

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.2, 8.3, 8.4]
                laravel: [10.*, 11.*, 12.*]
                stability: [prefer-lowest, prefer-stable]
                exclude:
                  - php: 8.4
                    laravel: 10.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: fileinfo, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Setup Problem Matches
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/phpunit
